expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Expense, Category
from .views import ExpenseListView, CategoryListView

urlpatterns = [
    path('expense/list/',
         ExpenseListView.as_view(),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
             model=Expense,
             fields='__all__',
             success_url=reverse_lazy('expenses:expense-list'),
             template_name='generic_update.html'
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
             model=Expense,
             fields='__all__',
             success_url=reverse_lazy('expenses:expense-list'),
             template_name='generic_update.html'
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
             model=Expense,
             success_url=reverse_lazy('expenses:expense-list'),
             template_name='generic_delete.html'
         ),
         name='expense-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('category/create/',
         CreateView.as_view(
             model=Category,
             fields='__all__',
             success_url=reverse_lazy('expenses:category-list'),
             template_name='generic_update.html'
         ),
         name='category-create'),
    path('category/<int:pk>/delete/',
         DeleteView.as_view(
             model=Category,
             success_url=reverse_lazy('expenses:category-list'),
             template_name='generic_delete.html'
         ),
         name='category-delete'),
    path('category/<int:pk>/edit/',
         UpdateView.as_view(
             model=Category,
             fields='__all__',
             success_url=reverse_lazy('expenses:category-list'),
             template_name='generic_update.html'
         ),
         name='category-edit'),
]

project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')),
]

expenses/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk')

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True, related_name='expense_category')

    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

expenses/forms.py
from django import forms
from .models import Expense, Category


class ExpenseSearchForm(forms.ModelForm):
    ORDER_BY_CHOICES = [
        ('category__name', 'Category A-Z'),
        ('-category__name', 'Category Z-A'),
        ('-date', 'Date Descending'),
        ('date', 'Date Ascending'),
    ]

    class Meta:
        model = Expense
        fields = ('name',)

    date_from = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    date_to = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    categories = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=Category.objects.all(),
        required=False,
    )
    order_by = forms.ChoiceField(
        choices=ORDER_BY_CHOICES,
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False

    def clean(self):
        cleaned_data = super().clean()
        date_from = cleaned_data.get('date_from')
        date_to = cleaned_data.get('date_to')

        if date_from and date_to:
            if date_to < date_from:
                raise forms.ValidationError(
                    "The end date must be later than the start date."
                )

        return cleaned_data

expenses/views.py
from django.db.models import Q
from django.views.generic import UpdateView
from django.views.generic.list import ListView

from .forms import ExpenseSearchForm
from .models import Expense, Category
from .reports import summary_per_category, total_amount_spend, summary_per_month


class ExpenseListView(ListView):
    model = Expense
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list

        form = ExpenseSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get('name', '').strip()
            date_from = form.cleaned_data.get('date_from')
            date_to = form.cleaned_data.get('date_to')
            categories = form.cleaned_data.get('categories')
            order_by = form.cleaned_data.get('order_by')

            filters = Q()

            if name:
                filters &= Q(name__icontains=name)

            if categories:
                filters &= Q(category__in=categories)

            if date_from and date_to:
                filters &= Q(date__gte=date_from, date__lte=date_to)
            elif date_from:
                filters &= Q(date__gte=date_from)
            elif date_to:
                filters &= Q(date__lte=date_to)

            queryset = queryset.filter(filters)

            if order_by:
                queryset = queryset.order_by(order_by)

        query_params = self.request.GET.copy()

        if 'page' in query_params:
            query_params.pop('page')

        search_params = query_params.urlencode()
        return super().get_context_data(
            form=form,
            object_list=queryset,
            summary_per_category=summary_per_category(queryset),
            search_params=search_params,
            current_url=self.request.path,
            total_amount_spend=total_amount_spend(queryset),
            summary_per_month=summary_per_month(queryset),
            **kwargs
        )


class CategoryListView(ListView):
    model = Category
    paginate_by = 5

expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'expenses:category-create' %}">add</a>

<table border="1">
	<thead>
		<tr>
			<th>name</th>
			<th>actions</th>
			<th>number of expenses</th>
		</tr>
	</thead>
	<tbody>
		{% for obj in object_list %}
		<tr>
			<td>
				{{obj.name}}
			</td>
			<td>
				<a href="{% url 'expenses:category-edit' obj.id %}">edit</a>
				<a href="{% url 'expenses:category-delete' obj.id %}">delete</a>
			</td>
			<td>
				{{obj.expense_category.all.count}}
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'expenses:expense-create' %}">add</a>

<form method="get" action="">
    {{form.as_p}}
    <button type="submit">search</button>
</form>
<br>
<table border="1">
    <caption>Expenses</caption>
    <thead>
    <tr>
        <th>no.</th>
        <th>category</th>
        <th>name</th>
        <th>amount</th>
        <th>date</th>
        <th>actions</th>
    </tr>
    </thead>
    <tbody>

    {% for obj in object_list %}
    <tr>
        <td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
        <td>{{ obj.category|default:"-" }}</td>
        <td>{{ obj.name|default:"-" }}</td>
        <td>{{ obj.amount|floatformat:2 }}</td>
        <td>{{obj.date}}</td>
        <td>
            <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
            <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
        </td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="5">no items</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% include "_pagination.html" %}
<hr>
<table border="1">
    <caption>Summary per category</caption>
    <tr>
        {% for category, total in summary_per_category.items %}
    <tr>
        <td>{{category}}:</td>
        <td>{{total|floatformat:2}}</td>
    </tr>
    {% endfor %}
    <tr>
        <td>

            Total amount spend:
        </td>
        <td>
            {{ total_amount_spend|floatformat:2 }}
        </td>
    </tr>
</table>
<table border="1">
    <caption>Summary per month</caption>
    <tr>
        <th>Month</th>
        <th>Total Amount</th>
    </tr>
    {% for item in summary_per_month %}
    <tr>
        <td>{{ item.month|date:"Y-m" }}</td>
        <td>{{ item.total|floatformat:2 }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% if page_obj.has_previous %}
            <a href="?page=1&{{ search_params }}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&{{ search_params }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&{{ search_params }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}&{{ search_params }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'expenses:expense-list' %}">Expenses</a> | 
	<a href="{% url 'expenses:category-list' %}">Categories</a> | 
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}